import { createAction } from 'redux-actions';

export const HANDLE_REGISTRATION_FORM_CHANGE = createAction('HANDLE_REGISTRATION_FORM_CHANGE');
export const HANDLE_REGISTRATION_FORM_REQUEST = createAction('HANDLE_REGISTRATION_FORM_REQUEST');
export const HANDLE_REGISTRATION_FORM_SUCCESS = createAction('HANDLE_REGISTRATION_FORM_SUCCESS');
export const HANDLE_REGISTRATION_FORM_FAIL = createAction('HANDLE_REGISTRATION_FORM_FAIL');

